import {
  VISA_OVERSTAY_DESCRIPTION,
  VISA_OVERSTAY_FEATURE_IMAGE,
  VISA_OVERSTAY_FEATURE_IMAGE_ALT,
  VISA_OVERSTAY_TITLE,
} from "./visaOverstayMeta";
import {
  ENTREPRENEUR_ARTICLE_DESCRIPTION,
  ENTREPRENEUR_ARTICLE_TITLE,
  ENTREPRENEUR_FEATURE_IMAGE,
  ENTREPRENEUR_FEATURE_IMAGE_ALT,
  ENTREPRENEUR_FEATURE_IMAGE_CAPTION,
  ENTREPRENEUR_FEATURE_IMAGE_DESCRIPTION,
  ENTREPRENEUR_FEATURE_IMAGE_TITLE,
  ENTREPRENEUR_SLUG,
} from "./entrepreneurVisaMeta";
import {
  CRIMINAL_CHARGES_ARTICLE_DESCRIPTION,
  CRIMINAL_CHARGES_ARTICLE_TITLE,
  CRIMINAL_CHARGES_FEATURE_IMAGE,
  CRIMINAL_CHARGES_FEATURE_IMAGE_ALT,
  CRIMINAL_CHARGES_FEATURE_IMAGE_CAPTION,
  CRIMINAL_CHARGES_FEATURE_IMAGE_DESCRIPTION,
  CRIMINAL_CHARGES_FEATURE_IMAGE_TITLE,
  CRIMINAL_CHARGES_SLUG,
} from "./criminalChargesMeta";
import {
  ADMIN_PROCESSING_ARTICLE_DESCRIPTION,
  ADMIN_PROCESSING_ARTICLE_TITLE,
  ADMIN_PROCESSING_FEATURE_IMAGE,
  ADMIN_PROCESSING_FEATURE_IMAGE_ALT,
  ADMIN_PROCESSING_FEATURE_IMAGE_CAPTION,
  ADMIN_PROCESSING_FEATURE_IMAGE_DESCRIPTION,
  ADMIN_PROCESSING_FEATURE_IMAGE_TITLE,
  ADMIN_PROCESSING_SLUG,
} from "./administrativeProcessingMeta";
import {
  USCIS_INTERVIEW_ARTICLE_DESCRIPTION,
  USCIS_INTERVIEW_ARTICLE_TITLE,
  USCIS_INTERVIEW_FEATURE_IMAGE,
  USCIS_INTERVIEW_FEATURE_IMAGE_ALT,
  USCIS_INTERVIEW_FEATURE_IMAGE_CAPTION,
  USCIS_INTERVIEW_FEATURE_IMAGE_DESCRIPTION,
  USCIS_INTERVIEW_FEATURE_IMAGE_TITLE,
  USCIS_INTERVIEW_SLUG,
} from "./uscisInterviewMeta";
import {
  TRAVEL_RESTRICTIONS_ARTICLE_DESCRIPTION,
  TRAVEL_RESTRICTIONS_ARTICLE_TITLE,
  TRAVEL_RESTRICTIONS_FEATURE_IMAGE,
  TRAVEL_RESTRICTIONS_FEATURE_IMAGE_ALT,
  TRAVEL_RESTRICTIONS_FEATURE_IMAGE_CAPTION,
  TRAVEL_RESTRICTIONS_FEATURE_IMAGE_DESCRIPTION,
  TRAVEL_RESTRICTIONS_FEATURE_IMAGE_TITLE,
  TRAVEL_RESTRICTIONS_SLUG,
} from "./travelRestrictionsMeta";
import {
  PENDING_CASE_WORK_ARTICLE_DESCRIPTION,
  PENDING_CASE_WORK_ARTICLE_TITLE,
  PENDING_CASE_WORK_FEATURE_IMAGE,
  PENDING_CASE_WORK_FEATURE_IMAGE_ALT,
  PENDING_CASE_WORK_FEATURE_IMAGE_CAPTION,
  PENDING_CASE_WORK_FEATURE_IMAGE_DESCRIPTION,
  PENDING_CASE_WORK_FEATURE_IMAGE_TITLE,
  PENDING_CASE_WORK_SLUG,
} from "./whileYourImmigrationCaseIsPendingMeta";
import {
  WAIVER_GUIDE_ARTICLE_DESCRIPTION,
  WAIVER_GUIDE_ARTICLE_TITLE,
  WAIVER_GUIDE_FEATURE_IMAGE,
  WAIVER_GUIDE_FEATURE_IMAGE_ALT,
  WAIVER_GUIDE_FEATURE_IMAGE_CAPTION,
  WAIVER_GUIDE_FEATURE_IMAGE_DESCRIPTION,
  WAIVER_GUIDE_FEATURE_IMAGE_TITLE,
  WAIVER_GUIDE_SLUG,
} from "./waiverOfInadmissibilityMeta";

export const staticBlogs = [
  {
    slug: WAIVER_GUIDE_SLUG,
    title: WAIVER_GUIDE_ARTICLE_TITLE,
    body: WAIVER_GUIDE_ARTICLE_DESCRIPTION,
    createdAt: "2026-06-29",
    published: true,
    featuredImage: {
      image: {
        url: WAIVER_GUIDE_FEATURE_IMAGE,
      },
      altText: WAIVER_GUIDE_FEATURE_IMAGE_ALT,
      title: WAIVER_GUIDE_FEATURE_IMAGE_TITLE,
      description: WAIVER_GUIDE_FEATURE_IMAGE_DESCRIPTION,
      caption: WAIVER_GUIDE_FEATURE_IMAGE_CAPTION,
    },
  },
  {
    slug: PENDING_CASE_WORK_SLUG,
    title: PENDING_CASE_WORK_ARTICLE_TITLE,
    body: PENDING_CASE_WORK_ARTICLE_DESCRIPTION,
    createdAt: "2026-06-21",
    published: true,
    featuredImage: {
      image: {
        url: PENDING_CASE_WORK_FEATURE_IMAGE,
      },
      altText: PENDING_CASE_WORK_FEATURE_IMAGE_ALT,
      title: PENDING_CASE_WORK_FEATURE_IMAGE_TITLE,
      description: PENDING_CASE_WORK_FEATURE_IMAGE_DESCRIPTION,
      caption: PENDING_CASE_WORK_FEATURE_IMAGE_CAPTION,
    },
  },
  {
    slug: TRAVEL_RESTRICTIONS_SLUG,
    title: TRAVEL_RESTRICTIONS_ARTICLE_TITLE,
    body: TRAVEL_RESTRICTIONS_ARTICLE_DESCRIPTION,
    createdAt: "2026-06-15",
    published: true,
    featuredImage: {
      image: {
        url: TRAVEL_RESTRICTIONS_FEATURE_IMAGE,
      },
      altText: TRAVEL_RESTRICTIONS_FEATURE_IMAGE_ALT,
      title: TRAVEL_RESTRICTIONS_FEATURE_IMAGE_TITLE,
      description: TRAVEL_RESTRICTIONS_FEATURE_IMAGE_DESCRIPTION,
      caption: TRAVEL_RESTRICTIONS_FEATURE_IMAGE_CAPTION,
    },
  },
  {
    slug: USCIS_INTERVIEW_SLUG,
    title: USCIS_INTERVIEW_ARTICLE_TITLE,
    body: USCIS_INTERVIEW_ARTICLE_DESCRIPTION,
    createdAt: "2026-06-07",
    published: true,
    featuredImage: {
      image: {
        url: USCIS_INTERVIEW_FEATURE_IMAGE,
      },
      altText: USCIS_INTERVIEW_FEATURE_IMAGE_ALT,
      title: USCIS_INTERVIEW_FEATURE_IMAGE_TITLE,
      description: USCIS_INTERVIEW_FEATURE_IMAGE_DESCRIPTION,
      caption: USCIS_INTERVIEW_FEATURE_IMAGE_CAPTION,
    },
  },
  {
    slug: ADMIN_PROCESSING_SLUG,
    title: ADMIN_PROCESSING_ARTICLE_TITLE,
    body: ADMIN_PROCESSING_ARTICLE_DESCRIPTION,
    createdAt: "2026-05-25",
    published: true,
    featuredImage: {
      image: {
        url: ADMIN_PROCESSING_FEATURE_IMAGE,
      },
      altText: ADMIN_PROCESSING_FEATURE_IMAGE_ALT,
      title: ADMIN_PROCESSING_FEATURE_IMAGE_TITLE,
      description: ADMIN_PROCESSING_FEATURE_IMAGE_DESCRIPTION,
      caption: ADMIN_PROCESSING_FEATURE_IMAGE_CAPTION,
    },
  },
  {
    slug: CRIMINAL_CHARGES_SLUG,
    title: CRIMINAL_CHARGES_ARTICLE_TITLE,
    body: CRIMINAL_CHARGES_ARTICLE_DESCRIPTION,
    createdAt: "2026-05-23",
    published: true,
    featuredImage: {
      image: {
        url: CRIMINAL_CHARGES_FEATURE_IMAGE,
      },
      altText: CRIMINAL_CHARGES_FEATURE_IMAGE_ALT,
      title: CRIMINAL_CHARGES_FEATURE_IMAGE_TITLE,
      description: CRIMINAL_CHARGES_FEATURE_IMAGE_DESCRIPTION,
      caption: CRIMINAL_CHARGES_FEATURE_IMAGE_CAPTION,
    },
  },
  {
    slug: ENTREPRENEUR_SLUG,
    title: ENTREPRENEUR_ARTICLE_TITLE,
    body: ENTREPRENEUR_ARTICLE_DESCRIPTION,
    createdAt: "2026-05-14",
    published: true,
    featuredImage: {
      image: {
        url: ENTREPRENEUR_FEATURE_IMAGE,
      },
      altText: ENTREPRENEUR_FEATURE_IMAGE_ALT,
      title: ENTREPRENEUR_FEATURE_IMAGE_TITLE,
      description: ENTREPRENEUR_FEATURE_IMAGE_DESCRIPTION,
      caption: ENTREPRENEUR_FEATURE_IMAGE_CAPTION,
    },
  },
  {
    slug: "visa-overstay",
    title: VISA_OVERSTAY_TITLE,
    body: VISA_OVERSTAY_DESCRIPTION,
    createdAt: "2026-05-10",
    published: true,
    featuredImage: {
      image: {
        url: VISA_OVERSTAY_FEATURE_IMAGE,
      },
      altText: VISA_OVERSTAY_FEATURE_IMAGE_ALT,
    },
  },
];

export function getPublishedBlogsWithStatic(blogPostData) {
  const blogsBySlug = new Map();
  const publishedBlogs = [
    ...staticBlogs,
    ...(blogPostData?.data?.filter((blog) => blog.published === true) || []),
  ];

  publishedBlogs.forEach((blog) => {
    if (blog?.slug && !blogsBySlug.has(blog.slug)) {
      blogsBySlug.set(blog.slug, blog);
    }
  });

  return [...blogsBySlug.values()].sort(
    (a, b) => new Date(b.createdAt) - new Date(a.createdAt)
  );
}
