import { Mulish, Bitter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import MainNavbar from "@/components/MainNavbar";
import Footer from "@/components/Footer";

const bitter = Bitter({ subsets: ["latin"] });
const mulish = Mulish({ subsets: ["latin"] });

export const metadata = {
  title: "Trip-Law",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body className={mulish.className}>
        <Providers>
          <div className="text-black bg-white overflow-x-hidden">
            <MainNavbar />
            {children}
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
